version: '3'


services:
    django:
        build: .
        command: >
            sh -c "
            python manage.py makemigrations --noinput && python manage.py migrate --noinput &&
            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - .env
        networks:
            - some_network
    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        env_file:
            - .env
        networks:
            - some_network
    redis:
        image: 'redis:alpine'
        hostname: redis
        command: redis-server
        networks:
            - some_network
        ports:
            - '6379:6379'
    celery:
        build: .
        command: >
            sh -c "
            celery -A celery worker --loglevel=info &&
            celery -A celery beat --loglevel=info"
        depends_on:
            - db
            - redis
            - django
        env_file:
            - .env
        networks:
            - some_network
    flower:
        image: mher/flower
        command: sh -c "sleep 10 && flower --broker=redis://redis:6379/0"
        ports:
            - "5555:5555"
        depends_on:
            - celery
            - redis


networks:
    some_network:
        driver: bridge

volumes:
    postgres_data: