# Generated by Django 4.2.7 on 2023-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('proj_name', models.CharField(max_length=255)),
                ('priority_name', models.CharField(max_length=255)),
                ('subtask', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('endpoint', models.TextField()),
                ('template', models.TextField()),
                ('callback', models.URLField()),
                ('filters', models.ManyToManyField(to='app_hooks.filters')),
            ],
        ),
    ]
