# Generated by Django 4.0 on 2024-02-05 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbededFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255, null=True)),
                ('inline', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Embeded Field',
                'verbose_name_plural': 'Embeded Fields',
            },
        ),
        migrations.CreateModel(
            name='EmbededFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='Icon_URL')),
            ],
            options={
                'verbose_name': 'Embeded Footer',
                'verbose_name_plural': 'Embeded Footers',
            },
        ),
        migrations.CreateModel(
            name='EndpointInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('callback', models.URLField(verbose_name='Callback')),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'All Endpoints',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('data', models.JSONField(blank=True, default=list, max_length=255, null=True, verbose_name='Filter Data')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
            },
        ),
        migrations.CreateModel(
            name='MiddlewaresBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Middleware name')),
                ('type', models.CharField(choices=[('task_stat', 'Статистика задач'), ('release_stat', 'Статистика релизов')], max_length=255, verbose_name='Middleware Class Type')),
            ],
            options={
                'verbose_name': 'Middleware',
                'verbose_name_plural': 'Middlewares',
            },
        ),
        migrations.CreateModel(
            name='EndpointDirect',
            fields=[
                ('endpointinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_hooks.endpointinterface')),
                ('template', models.TextField(verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Direct Endpoint',
                'verbose_name_plural': 'Direct Endpoints',
            },
            bases=('app_hooks.endpointinterface',),
        ),
        migrations.CreateModel(
            name='ReleaseStatMiddleware',
            fields=[
                ('middlewaresbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_hooks.middlewaresbase')),
                ('project_id', models.CharField(blank=True, max_length=255, verbose_name='Project')),
                ('version', models.CharField(blank=True, max_length=255, verbose_name='Version')),
            ],
            bases=('app_hooks.middlewaresbase',),
        ),
        migrations.CreateModel(
            name='TaskStatMiddleware',
            fields=[
                ('middlewaresbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_hooks.middlewaresbase')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='Task id')),
                ('frontend_score', models.CharField(blank=True, max_length=255, verbose_name='Front score')),
                ('backend_score', models.CharField(blank=True, max_length=255, verbose_name='Back score')),
            ],
            bases=('app_hooks.middlewaresbase',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('draft', models.BooleanField(default=True)),
                ('endpoints', models.ManyToManyField(blank=True, related_name='endpoints', to='app_hooks.EndpointInterface')),
                ('filters', models.ManyToManyField(related_name='events', to='app_hooks.Filter')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='endpointinterface',
            name='middleware',
            field=models.ManyToManyField(related_name='middleware', to='app_hooks.MiddlewaresBase'),
        ),
        migrations.AddField(
            model_name='endpointinterface',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='EndpointEmbeded',
            fields=[
                ('endpointinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_hooks.endpointinterface')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='Url')),
                ('color', models.CharField(max_length=15, verbose_name='Color')),
                ('thumbnail', models.URLField(blank=True, null=True, verbose_name='Thumbnail')),
                ('author', models.TextField(null=True, verbose_name='Author')),
                ('fields', models.ManyToManyField(related_name='endpoint', to='app_hooks.EmbededFields')),
                ('footer', models.ManyToManyField(related_name='footers', to='app_hooks.EmbededFooter')),
            ],
            options={
                'verbose_name': 'Embeded Endpoint',
                'verbose_name_plural': 'Embeded Endpoints',
            },
            bases=('app_hooks.endpointinterface',),
        ),
    ]
