# Generated by Django 4.2.7 on 2023-12-07 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict, verbose_name='Filter Data'), default=list, size=None),
        ),
    ]
