# Generated by Django 4.0 on 2024-02-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatmiddleware',
            name='middlewaresbase_ptr',
        ),
        migrations.RemoveField(
            model_name='middlewaresbase',
            name='name',
        ),
        migrations.AlterField(
            model_name='middlewaresbase',
            name='type',
            field=models.CharField(choices=[('task_stat', 'Статистика задач'), ('release_stat', 'Статистика релизов')], default='task_stat', max_length=255, verbose_name='Middleware Class Type'),
        ),
        migrations.DeleteModel(
            name='ReleaseStatMiddleware',
        ),
        migrations.DeleteModel(
            name='TaskStatMiddleware',
        ),
    ]
