# Generated by Django 4.2.7 on 2023-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endpoint',
            field=models.CharField(verbose_name='Endpoint'),
        ),
    ]
