# Generated by Django 4.2.7 on 2023-12-07 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hooks', '0002_alter_filter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=list, null=True, verbose_name='Filter Data'), size=None),
        ),
    ]
