# Generated by Django 4.2.7 on 2023-12-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hooks', '0003_alter_filter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='data',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Filter Data'),
        ),
    ]
